# Generated by Django 2.1.4 on 2018-12-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='biography',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='github',
            new_name='phone',
        ),
    ]
