# Generated by Django 2.1.4 on 2018-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181215_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
