# Generated by Django 2.1.4 on 2018-12-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181214_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bathrooms',
            new_name='bathroom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bedrooms',
            new_name='bedroom',
        ),
    ]
