# Generated by Django 2.1.4 on 2018-12-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181213_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passowrd',
            new_name='password',
        ),
    ]
