# Generated by Django 2.1.4 on 2018-12-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
